---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---



library(igraph)
#number of nodes/people in the network
size=50
# graph of random world network (used)
g = erdos.renyi.game(size, 0.1)

plot(g)

# small-world network
#g = rewire.edges(erdos.renyi.game(size, 0.1), prob = 0.8 )
# scale-free network
#g = barabasi.game(size) ; plot(g)

#initiate diffusers (initally infected)
seeds_num = 1
set.seed(2014); diffusers = sample(V(g),seeds_num) ; diffusers
infected =list()
infected[[1]]= diffusers

# set the color
E(g)$color = "grey"
V(g)$color = "white"

set.seed(2014); layout.old = layout.fruchterman.reingold(g, niter = 1000)
V(g)$color[V(g)%in%diffusers] = "red"
plot(g, layout =layout.old)

# for example, set percolation probability
p = 0.128
coins = c(rep(1, p*1000), rep(0,(1-p)*1000))
n = length(coins)
sample(coins, 1, replace=TRUE, prob=rep(1/n, n))

#update diffusers (new infections)
# function for updating the diffusers
update_diffusers = function(diffusers){
  nearest_neighbors = neighborhood(g, 1, diffusers)
  nearest_neighbors = data.frame(table(unlist(nearest_neighbors)))
  nearest_neighbors = subset(nearest_neighbors, !(nearest_neighbors[,1]%in%diffusers))
  # toss the coins
  toss = function(freq) {
    tossing = NULL
    for (i in 1:freq ) tossing[i] = sample(coins, 1, replace=TRUE, prob=rep(1/n, times=n))
    tossing = sum(tossing)
    return (tossing)
  }
  keep = unlist(lapply(nearest_neighbors[,2], toss))
  new_infected = as.numeric(as.character(nearest_neighbors[,1][keep >= 1]))
  class(new_infected) <- "igraph.vs"
  diffusers = unique(c(diffusers, new_infected))
  return(diffusers)
  }

#Start the infection
i = 1
while(length(infected[[i]]) < size){
  infected[[i+1]] = sort(update_diffusers(infected[[i]]))
  cat(length(infected[[i+1]]), "\n")
  i = i + 1
}
#visuals 
E(g)$color = "blueviolet"
V(g)$color = "white"
set.seed(2014); layout.old = layout.fruchterman.reingold(g)
V(g)$color[V(g)%in%diffusers] = "red"
plot(g, layout =layout.old)

#plots
plot_time_series = function(infected, m){
  num_cum = unlist(lapply(1:m, 
            function(x) length(infected[[x]]) ))
  p_cum = num_cum/size
  p = diff(c(0, p_cum))
  time = 1:m
  plot(p_cum~time, type = "b", 
       ylab = "CDF", xlab = "Time",
       xlim = c(0,i), ylim =c(0,1))
  plot(p~time, type = "h", frame.plot = FALSE,
       ylab = "PDF", xlab = "Time",
       xlim = c(0,i), ylim =c(0,1))
}
plot_time_series(infected, length(infected))

#animated
library(animation)
saveGIF({
  ani.options(interval = 0.5, convert = shQuote("C:/Program Files/ImageMagick-6.8.8-Q16/convert.exe"))
  # start the plot
  m = 1
  while(m <= length(infected)){
    # start the plot
    layout(matrix(c(1, 2, 1, 3), 2,2, byrow = TRUE), widths=c(3,1), heights=c(1, 1))
    V(g)$color <- "white"
    V(g)$color[V(g)%in%infected[[m]]] = "red"
    num_cum = unlist(lapply(1:m, function(x) length(infected[[x]]) ))
    p_cum = num_cum/size
    p = diff(c(0, p_cum))
    time = 1:m
    plot(g, layout =layout.old, edge.arrow.size=0.2)
    title(paste("ER Random Network \n Day", m))
    plot(p_cum~time, type = "b", ylab = "CDF", xlab = "Time",
         xlim = c(0,i), ylim =c(0,1))
    plot(p~time, type = "h", ylab = "PDF", xlab = "Time",
         xlim = c(0,i), ylim =c(0,1), frame.plot = FALSE)
    m = m + 1}
}, ani.width = 800, ani.height = 500)

