---
title: "R Notebook"
output: html_notebook
---



```{r}

library(ggplot2)


data<-read.csv("C:/Users/Kashyap/Documents/stats_337/cleaned_sars_data.csv", header=TRUE)
east_asia = data[data$region == 'east_asian',]
south_east_asia = data[data$region == 'south_east_asian',]
western_europe = data[data$region == 'east_asian',]

```



```{r}


ggplot(data=east_asia, aes(x=1:nrow(east_asia), y=cases)) +
  geom_line(color="red", linetype = "dashed") +
  geom_point() + labs(y= "Cumulative Cases", x = "Days in outbreak (From March, 17 2003)")
ggsave(filename="C:/Users/Kashyap/Documents/stats_337/east_asia_cumulative_cases.jpg", plot=last_plot())

ggplot(data=east_asia, aes(x=1:nrow(east_asia), y=delta.cases)) +
  geom_point()

```


```{r}


ggplot(data=south_east_asia, aes(x=1:nrow(south_east_asia), y=cases)) +
  geom_line(color="red", linetype = "dashed") +
  geom_point()  + labs(y= "Cumulative Cases", x = "Days in outbreak (From March, 17 2003)")
ggsave(filename="C:/Users/Kashyap/Documents/stats_337/south_east_asia_cumulative_cases.jpg", plot=last_plot())

ggplot(data=south_east_asia, aes(x=1:nrow(south_east_asia), y=delta.cases)) +
  geom_point()

```



```{r}


ggplot(data=western_europe, aes(x=1:nrow(western_europe), y=cases)) +
  geom_line(color="red", linetype = "dashed") +
  geom_point() + labs(y= "Cumulative Cases", x = "Days in outbreak (From March, 17 2003)")
ggsave(filename="C:/Users/Kashyap/Documents/stats_337/western_europe_cumulative_cases.jpg", plot=last_plot())

ggplot(data=western_europe, aes(x=1:nrow(western_europe), y=delta.cases)) +
  geom_point()

```














