---
title: "sir_model"
output: pdf_document
---

```{r}

sir_1 <- function(beta, gamma, S0, I0, R0, times) {
  require(deSolve) # for the "ode" function
  
# the differential equations:
  sir_equations <- function(time, variables, parameters) {
  with(as.list(c(variables, parameters)), {
    dS <- -beta * I * S
    dI <-  beta * I * S - gamma * I
    dR <-  gamma * I
    return(list(c(dS, dI, dR)))
  })
  }
  
# the parameters values:
  parameters_values <- c(beta  = beta, gamma = gamma)

# the initial values of variables:
  initial_values <- c(S = S0, I = I0, R = R0)
  
# solving
  out <- ode(initial_values, times, sir_equations, parameters_values)

# returning the output:
  as.data.frame(out)
}

```



```{r}

sir_values_1 <- sir_1(beta = 0.048, gamma = 0.000014, S0 = 10000, I0 = 1, R0 = 0, times = seq(0, 50))
# r_not <- (999 + 1) * parameters_values["beta"] / parameters_values["gamma"]


```


```{r}

with(sir_values_1, {
# plotting the time series of susceptibles:
  plot(time, S, type = "l", col = "blue",
       xlab = "time (days)", ylab = "number of people")
# adding the time series of infectious:
  lines(time, I, col = "red")
# adding the time series of recovered:
  lines(time, R, col = "green")
})

# adding a legend:
legend("right", c("susceptibles", "infectious", "recovered"),
       col = c("blue", "red", "green"), lty = 1, bty = "n")

```


```{r}
library(shinySIR)

run_shiny(model = "SIR")


```
```{r}

## Load deSolve package
library(deSolve)

## Create an SIR function
sir <- function(time, state, parameters) {

  with(as.list(c(state, parameters)), {

    dS <- -beta * S * I
    dI <-  beta * S * I - gamma * I
    dR <-                 gamma * I

    return(list(c(dS, dI, dR)))
  })
}

### Set parameters
## Proportion in each compartment: Susceptible 0.999999, Infected 0.000001, Recovered 0
init       <- c(S = 1-1e-6, I = 1e-6, R = 0.0)
## beta: infection parameter; gamma: recovery parameter
parameters <- c(beta = 0.30, gamma = 0.14)
## Time frame
times      <- seq(0, 403, by = 1)

## Solve using ode (General Solver for Ordinary Differential Equations)
out <- ode(y = init, times = times, func = sir, parms = parameters)
## change to data frame
out <- as.data.frame(out)
## Delete time variable
out$time <- NULL
## Show data
head(out, 10)



```

```{r}

## Plot
matplot(x = times, y = out, type = "l",
        xlab = "Time", ylab = "Susceptible and Recovered", main = "SIR Model",
        col = 2:4)

## Add legend
legend(200, 1, c("Susceptible", "Infected", "Recovered"), pch = 1, col = 2:4, bty = "n")


```


```{r}

data<-read.csv("C:/Users/Kashyap/Documents/stats_337/cleaned_sars_data.csv", header=TRUE)
east_asia = data[data$region == 'east_asian',]
south_east_asia = data[data$region == 'south_east_asian',]
western_europe = data[data$region == 'east_asian',]

east_asia_cases = east_asia$cases

east_asia_sir_cases = list()
east_asia_sir_cases[[1]] = 0
i = 2
for(case in out$I){
  prev_value = east_asia_sir_cases[i-1]
  new_case_value = (case * 10000) - prev_value[[1]]
  east_asia_sir_cases[[i]] = new_case_value + (case * 10000)
  
  i = i + 1
}
east_asia_sir_cases[[1]] = NULL
chisq.test(east_asia_cases, east_asia_sir_cases)



```


















